name: scrumlab_link
description: A simple widget for simulating links in Flutter
version: 2.0.0
homepage: https://github.com/scrum-lab/scrumlab_link_flutter

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0

dev_dependencies:
  test: ^1.0.0
